language: cpp
env:
  global:
    - APT_DEPENDENCIES="cmake cmake-data doxygen libltdl-dev libboost-all-dev liblog4cxx10-dev libblas-dev liblapack-dev libmumps-seq-dev gfortran libqhull-dev"
    - HOMEBREW_DEPENDENCIES="doxygen log4cxx ipopt openblas mumps qhull"
    - GIT_DEPENDENCIES="roboptim/roboptim-core roboptim/roboptim-core-plugin-ipopt"
    - DEBSIGN_KEYID=5AE5CD75
    - PPA_URI="roboptim/ppa"
    - NSIQCPPSTYLE_FILEFILTERPATH=cmake/filefilter.txt
    - GH_USERNAME=thomas-moulard
    - GH_REPO=roboptim/roboptim-capsule
    - LCOV_IGNORE_RULES="*tests*"
    - secure: fURGUkCIPnZZ4G+Gaf9wMPH2P8sXiDA0kA1S6qVdCbenIyilRNnLmPiqHoqwtVEl4pqpdmRoFnMbJMGIuh+61gdo23+MZ1TBeNUp86nkH4v+qVRw5n1Nm2cKJZiqiuRHcTF3jVCVgx7eUvDkPAjJ9ff4vxB8sQhOQkQeGilJyak=
    - secure: TBMOOJtRFuQK9NWIlKuBg+/LiuTa8Hz+8PsnZB/vGlc4FpoRJkz7DmnQS/sCDxunhaXZX6rac7THzCn6lrp5wksXNRRqUwRiv+JixyE1WbAnn22JBEouhs4o4fjRtwPvvkH0+EpAxuSebltCESrdxfjjkeLine4CZvV0e6HPquw=
    - secure: ALE6izEg9T+fqCBUvvhKEgOgCnR+43DSOFT/DDBIj2hCXlf9R9dQ8upaG/6JXl08i5hwVRvQMK9+zJfU25cTTM/xpC8O/5G8t7pG9Y+/QeVOMbOCQnHMDe7dB8azO8CHnC91pP00ychf8KSL2Exz+o1k1fha/9BaZZDo5zCrKKU=
notifications:
  hipchat:
    rooms:
      - secure: YH0AqP/y2L3+YkHNezAOfBNMB5QkeEYE3z5NV5k7gxqaEPEklQeMrSHLZzN1TuSyms/RuiQ6Zj0QA9D2ZxioTxTqGUQbh5c+Ia5n5GTIJZYg24uVXPS1w6uFQSyVNIZE6tJGpgf0RHzeGtejRW7Q9Ppr6e55TBnBc53fGTqJyPs=
  email: roboptim@googlegroups.com
branches:
  only:
  - master
  - dev
  - debian
  - travis
before_install:
  - pip install --user codecov
  - ./.travis/dependencies/eigen-3.2
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then CC=gcc CXX=g++ ./.travis/dependencies/ipopt; fi
  - ./.travis/run  before_install
script:
  - . .travis/common.sh
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export LD_LIBRARY_PATH=`pkg-config --variable=plugindir roboptim-core`:$LD_LIBRARY_PATH; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then export DYLD_LIBRARY_PATH=`pkg-config --variable=plugindir roboptim-core`:$DYLD_LIBRARY_PATH; fi
  - ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
matrix:
  allow_failures:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - env: COVERITY_SCAN_BRANCH=1
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
      env: ENABLE_CXX11=1
    - os: linux
      dist: precise
      compiler: gcc
      env: MASTER_PPA="george-edison55/precise-backports"
    - os: linux
      dist: precise
      compiler: clang
      env: MASTER_PPA="george-edison55/precise-backports"
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc
